### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/flows'

### ISSUE THREAD

**Issue by NonlinearNimesh** [rpeden/prefect-docker-compose#3]
Hi everyone i am using the below docker-compose.yml for running orion, postgres, cli and agent (not using minio).
when i run python flow.py then it get run successfully
but,
when i trigger it using deployment id, then it throws this error
```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 262, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 247, in asyncnullcontext
    yield
  File "/usr/local/lib/python3.11/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments.py", line 170, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.11/site-packages/prefect/filesystems.py", line 143, in get_directory
    copytree(from_path, local_path, dirs_exist_ok=True)
  File "/usr/local/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/flows'
```
My flow is in this path : /home/ubuntu/prefect/flows/
Can anyone please tell me what i am doing wrong here.
Here is my modified docker compose
```
version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["orion"]
  
  ### MinIO for flow storage
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]

  ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2.7.7-python3.11
    restart: always
    volumes:
      - prefect:/home/ubuntu/prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      # If you want Orion to access Orion from anywhere other than the Docker host machine, you will need to change
      # PREFECT_API_URL to match the hostname/IP used to load the Orion UI in your web browser.
      - PREFECT_API_URL=http://192.168.243.24:4200/api
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["orion"]

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.7.7-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "test_queue"]
    environment:
      - PREFECT_API_URL=http://192.168.243.24:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["agent"]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.7.7-python3.11
    entrypoint: "bash"
    working_dir: "/flows"
    volumes:
      - /home/ubuntu/prefect/flows/:/flows
    environment:
      - PREFECT_API_URL=http://orion:4200/api
#       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["cli"]
      
volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network

```
And my triggering flow code and flow.py code
```
# trigger_flow.py
from prefect.client import get_client
import asyncio
import random
import uuid
async def trigger_flow_runs():
    client = get_client()
    d_id_list = 42fe128a-03ce-4bee-bb44-ba79243ef01a" #Deployment id
    t = await client.create_flow_run_from_deployment(deployment_id=d_id_list , name=str(uuid.uuid4))
if __name__ == "__main__":
    asyncio.run(trigger_flow_runs())

# flow.py
from prefect import flow, task

@task
def say_hello(name):
    print(f"hello {name}")

@task
def say_goodbye(name):
    print(f"goodbye {name}")

@flow(name="test flow")
def greetings(names=["arthur", "trillian", "ford", "marvin"]):
    for name in names:
        say_hello(name)
        say_goodbye(name)

if __name__ == "__main__":
    greetings(["arthur", "trillian", "ford", "marvin"])

```

Can anyone please help me where i am doing wrong in docker-compose. i want to trigger the flow.py wusing the deployment id from trigger_flow.py.

Thanks

**Comment by NonlinearNimesh** [comment]
solved, i have not configued minio

**Comment by ksuden** [comment]
@NonlinearNimesh Hello, I am stuck on this as well and was wondering if you could help me, since it seems you were able to get minio configuration to work. I am currently on the deployment step. The line that I am using is

`prefect deployment build -sb "remote-file-system/scrape-flow-block" -n "Scrape Deployment" -q "scrape_flow" "flow.py:scrape_flow"`

I am running this from inside the docker compose client by using the command docker-compose run cli. The error I am getting is:

`Script at 'flow.py' encountered an exception: NoCredentialsError('Unable to locate credentials')`

This seems to be in result to the deployment process not being able to find my credentials. However, I have set up a block via the prefect ui called scrape-flow-block. I set the key and secret key with json just as this githubs documentation says and I am still getting this error. From what I can tell, it seems like it is searching the actual flow.py script for credentials and is not finding any. When I look at my block, I see a note that says "paste this snippet into your flows to use this block":

`from prefect.filesystems import RemoteFileSystem

remote_file_system_block = RemoteFileSystem.load("scrape-flow-block")`

However, I am still getting the same error even if I add this snippet to my flows.py file. Do you remember if you saw this issue and how you fixed it? Would be much appreciated. Thanks!
